name: testing

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install the dev dependencies
      run: npm install
    - name: run unit tests with jest
      run: npm run test
